apiVersion: v1
kind: ConfigMap
metadata:
  name: train-cm
  labels:
    et/job-id: ""
    et/project-id: ""
    et/data-hash: ""
  ownerReferences:
    - apiVersion: batch/v1
      kind: Job
      name: ""
      uid: ""
data:
  train_py: "" # train_sh
